### ISSUE TITLE
New PM page 

### ISSUE THREAD

**Issue by TamaraG13** [atomiv/atomiv.github.io#186]
Cao Jelena,

Da li mozes da mi pomognes u kreiranju stranice za pitanja i odgovore oko PM?
 
Ja sam probala sama da uradim ali bezuspesno. Htela sam da to bude stranica na knowledge base-u, i da je nazovem Project Management basics ili tako nesto, jer se tu zaista nalaze osnove o project managementu. 
Ubacila bih je pre ili posle Overview-a.

Bilo bi odlicno ako bi mogla da snimis video kako se kreiraju stranice i sve sto je potrebno za to, i da se to ubaci u Wiki, mislim da bi bilo korisno za sve. Ja sam pokusala da kreiram stranicu prema https://github.com/atomiv/atomiv.github.io/wiki/Page-Structure ali nazalost, nisam se bas snasla.

Video je sjajna opcija, i mozes da koristis Loom ili Vidyard aplikaciju, i istaliras Google chrome ekstenziju, bice ti lakse.

Hvala unapred!

**Comment by jcupac** [comment]
File zavrsava sa .md
naprimer: pm-basics.md
