### ISSUE TITLE
Meeting with developers for Vue.js

### ISSUE THREAD

**Issue by TamaraG13** [atomiv/atomiv.github.io#191]
Cao Valentina,

pricala sam sa ovim bivsim kolegama, sto imaju neko znanje iz Vue.js, i oni bi voleli da cuju vise o tome, i da ucestvuju koliko mogu.

Da li mozemo da organizujemo sastanak sa njima? Oni rade do 5 ja mislim i jedan i drugi tako da bi bilo dobro neki dan predvece.

**Comment by valentinajemuovic** [comment]
Слажем се.
